export function Fonts() {
  return (
    <>
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-Bold.woff"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-BoldItalic.woff"
        as="font"
        crossOrigin=""
      />

      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-Light.woff"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-LightItalic.woff"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-Regular.woff"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-RegularItalic.woff"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-Bold.woff2"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-BoldItalic.woff2"
        as="font"
        crossOrigin=""
      />

      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-Light.woff2"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-LightItalic.woff2"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-Regular.woff2"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Aeonik/Aeonik-RegularItalic.woff2"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/GT Super/GT-Super-Display-Light-Italic.woff"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/GT Super/GT-Super-Display-Light-Italic.woff2"
        as="font"
        crossOrigin=""
      />
    </>
  );
}
