# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Hasura CI
        # You may pin to the exact commit or the version.
        uses: kevarifin14/hasura-ci-cd-action@c7ab0cc0fd2342f811502c9f8e7c969339d919b4
        # uses: GavinRay97/hasura-ci-cd-action@v1.3
        with:
          # The relative path from the root of your repo to where the Hasura project (containing config.yaml and your migrations/metadata folders) is located. For example, if your top-level directory contains a "hasura" folder, then this value should be ./hasura
          PATH_TO_HASURA_PROJECT_ROOT: ./packages/hasura
          # Version of Hasura CLI to download and use. Defaults to 'latest' if not set.
          HASURA_CLI_VERSION: v2.0.9
          # Optional overriding URL for the Hasura endpoint to call migrate apply and/or regression tests on. Will default to config.yaml value (as the CLI is run from the directory containing config.yaml).
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          # Optional overriding admin secret for the Hasura instance. Will default to config.yaml value (as the CLI is run from the directory containing config.yaml).
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          # Whether or not migrations should be run during CI/CD.
          HASURA_MIGRATIONS_ENABLED: true
